<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
include 'db_con.php';

$elements=array(
    array('name'=>'Hydrogen',
        'atm_no'=>'1',
        'symbol'=> 'H',
        'mass'=>'1',
        'type'=>'gas'),
    
    array(
     'name'=>'Helium',
        'atm_no'=>'3',
        'symbol'=> 'He',
        'mass'=>'4',
        'type'=>'nobel gas',   
    ),
     array(
     'name'=>'Lithium',
        'atm_no'=>'3',
        'symbol'=> 'Li',
        'mass'=>'7',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Beryllium',
        'atm_no'=>'4',
        'symbol'=> 'Be',
        'mass'=>'9',
        'type'=>'metal',   
    ),
     array(
     'name'=>'Boron',
        'atm_no'=>'5',
        'symbol'=> 'B',
        'mass'=>'11',
        'type'=>'metalloid',   
    ),
      array(
     'name'=>'Carbon',
        'atm_no'=>'6',
        'symbol'=> 'C',
        'mass'=>'12',
        'type'=>'non-metal',   
    ),
     array(
     'name'=>'Nitrogen',
        'atm_no'=>'7',
        'symbol'=> 'N',
        'mass'=>'14',
        'type'=>'non-metal',   
    ),
   array(
     'name'=>'Oxygen',
        'atm_no'=>'8',
        'symbol'=> 'O',
        'mass'=>'16',
        'type'=>'non-metal' ,  
    ), 
     array(
     'name'=>'Flourine',
        'atm_no'=>'9',
        'symbol'=> 'F',
        'mass'=>'19',
        'type'=>'non-metal',   
    ),
    
     array(
     'name'=>'Neon',
        'atm_no'=>'10',
        'symbol'=> 'Ne',
        'mass'=>'20',
        'type'=>'nobelgas',   
    ),
    
     array(
     'name'=>'Sodium',
        'atm_no'=>'11',
        'symbol'=> 'Na',
        'mass'=>'23',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Magnesium',
        'atm_no'=>'12',
        'symbol'=> 'Mg',
        'mass'=>'24',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Aluminium',
        'atm_no'=>'13',
        'symbol'=> 'Al',
        'mass'=>'27',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Silicon',
        'atm_no'=>'14',
        'symbol'=> 'Si',
        'mass'=>'28',
        'type'=>'non-metal' ,  
    ),
    array(
     'name'=>'Phosphorus',
        'atm_no'=>'15',
        'symbol'=> 'P',
        'mass'=>'31',
        'type'=>'non-metal',   
    ),
    array(
     'name'=>'Sulphur',
        'atm_no'=>'16',
        'symbol'=> 'S',
        'mass'=>'32',
        'type'=>'non-metal',   
    ),
     array(
     'name'=>'Chlorine',
        'atm_no'=>'17',
        'symbol'=> 'Cl',
        'mass'=>'35',
        'type'=>'non-metal',   
    ),
    array(
     'name'=>'argon',
        'atm_no'=>'18',
        'symbol'=> 'Ar',
        'mass'=>'40',
        'type'=>'nobelgas' ,  
    ),
     array(
     'name'=>'Potassium',
        'atm_no'=>'19',
        'symbol'=> 'K',
        'mass'=>'39',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Calcium',
        'atm_no'=>'20',
        'symbol'=> 'Ca',
        'mass'=>'40',
        'type'=>'metal',   
    ),
     array(
     'name'=>'Iron',
        'atm_no'=>'26',
        'symbol'=> 'Fe',
        'mass'=>'56',
        'type'=>'metal' ,  
    ),
    
     array(
     'name'=>'Copper',
        'atm_no'=>'29',
        'symbol'=> 'Cu',
        'mass'=>'63',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Zinc',
        'atm_no'=>'30',
        'symbol'=> 'Zn',
        'mass'=>'65',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Silver',
        'atm_no'=>'47',
        'symbol'=> 'Ag',
        'mass'=>'18',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Tungsten',
        'atm_no'=>'74',
        'symbol'=> 'W',
        'mass'=>'184',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Platinum',
        'atm_no'=>'78',
        'symbol'=> 'Pt',
        'mass'=>'195',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Gold',
        'atm_no'=>'79',
        'symbol'=> 'Au',
        'mass'=>'197',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Mercury',
        'atm_no'=>'80',
        'symbol'=> 'Hg',
        'mass'=>'201',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Lead',
        'atm_no'=>'82',
        'symbol'=> 'Pb',
        'mass'=>'207',
        'type'=>'metal',   
    ),
    array(
     'name'=>'Krypton',
        'atm_no'=>'36',
        'symbol'=> 'Kr',
        'mass'=>'84',
        'type'=>'nobelgas',   
    ),
    array(
     'name'=>'Xenon',
        'atm_no'=>'54',
        'symbol'=> 'Xe',
        'mass'=>'131',
        'type'=>'nobelgas' ,  
    ),
    array(
     'name'=>'Scandium',
        'atm_no'=>'21',
        'symbol'=> 'Sc',
        'mass'=>'44.9559',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Titanium',
        'atm_no'=>'22',
        'symbol'=> 'Ti',
        'mass'=>'47.867',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Vandanium',
        'atm_no'=>'23',
        'symbol'=> 'V',
        'mass'=>'50.9415',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Chromium',
        'atm_no'=>'24',
        'symbol'=> 'Cr',
        'mass'=>'51.9961',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Magnese',
        'atm_no'=>'25',
        'symbol'=> 'Mn',
        'mass'=>'54.938',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Cobalt',
        'atm_no'=>'27',
        'symbol'=> 'Co',
        'mass'=>'58.9332',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Nickel',
        'atm_no'=>'28',
        'symbol'=> 'Ni',
        'mass'=>'58.6934',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Gallium',
        'atm_no'=>'31',
        'symbol'=> 'Ga',
        'mass'=>'69.732',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Germanium',
        'atm_no'=>'32',
        'symbol'=> 'Ge',
        'mass'=>'72.64',
        'type'=>'metalloid' ,  
    ),
     array(
     'name'=>'Arsenic',
        'atm_no'=>'33',
        'symbol'=> 'As',
        'mass'=>'74.9216',
        'type'=>'metalloid' ,  
    ),
     array(
     'name'=>'Selenium',
        'atm_no'=>'34',
        'symbol'=> 'Se',
        'mass'=>'78.96',
        'type'=>'non-metal' ,  
    ),
    
     array(
     'name'=>'Bromine',
        'atm_no'=>'35',
        'symbol'=> 'Br',
        'mass'=>'79.904',
        'type'=>'non-metal' ,  
    ),
    array(
     'name'=>'Rubidium',
        'atm_no'=>'37',
        'symbol'=> 'Rb',
        'mass'=>'85.4678',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Strontium',
        'atm_no'=>'38',
        'symbol'=> 'Sr',
        'mass'=>'87.62',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Yttrium',
        'atm_no'=>'39',
        'symbol'=> 'Y',
        'mass'=>'88.9059',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Zirconium',
        'atm_no'=>'40',
        'symbol'=> 'Zr',
        'mass'=>'91.224',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Niobium',
        'atm_no'=>'41',
        'symbol'=> 'Nb',
        'mass'=>'92.9064',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Molybdenum',
        'atm_no'=>'42',
        'symbol'=> 'Mo',
        'mass'=>'95.94',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Technetium',
        'atm_no'=>'43',
        'symbol'=> 'Tc',
        'mass'=>'98',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Ruthenium',
        'atm_no'=>'44',
        'symbol'=> 'Ru',
        'mass'=>'101.07',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Rhodium',
        'atm_no'=>'45',
        'symbol'=> 'Rh',
        'mass'=>'102.9055',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Palladium',
        'atm_no'=>'46',
        'symbol'=> 'Pd',
        'mass'=>'106.42',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Cadmium',
        'atm_no'=>'48',
        'symbol'=> 'Cd',
        'mass'=>'112.411',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Indium',
        'atm_no'=>'49',
        'symbol'=> 'In',
        'mass'=>'114.818',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Tin',
        'atm_no'=>'50',
        'symbol'=> 'Sn',
        'mass'=>'118.71',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Antimony',
        'atm_no'=>'51',
        'symbol'=> 'Sb',
        'mass'=>'121.76',
        'type'=>'metalloid' ,  
    ),
       array(
     'name'=>'Tellurium',
        'atm_no'=>'52',
        'symbol'=> 'Te',
        'mass'=>'127.6',
        'type'=>'metalloid' ,  
    ),
      array(
     'name'=>'Iodine',
        'atm_no'=>'53',
        'symbol'=> 'I',
        'mass'=>'126.9045',
        'type'=>'non-metal' ,  
    ),
      array(
     'name'=>'Cesium',
        'atm_no'=>'55',
        'symbol'=> 'Cs',
        'mass'=>'132.9055',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Barium',
        'atm_no'=>'56',
        'symbol'=> 'Ba',
        'mass'=>'137.327',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Lanthanum',
        'atm_no'=>'57',
        'symbol'=> 'La',
        'mass'=>'138.9055',
        'type'=>'metal' ,  
    ),
    array(
     'name'=>'Cerium',
        'atm_no'=>'58',
        'symbol'=> 'Ce',
        'mass'=>'140.116',
        'type'=>'' ,  
    ),
     array(
     'name'=>'praseodynium',
        'atm_no'=>'59',
        'symbol'=> 'Pr',
        'mass'=>'140.9077',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Neodymium',
        'atm_no'=>'60',
        'symbol'=> 'Nd',
        'mass'=>'144.24',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Promethium',
        'atm_no'=>'61',
        'symbol'=> 'Pm',
        'mass'=>'145',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Samarium',
        'atm_no'=>'62',
        'symbol'=> 'Sm',
        'mass'=>'150.36',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Europium',
        'atm_no'=>'63',
        'symbol'=> 'Eu',
        'mass'=>'151.964',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Gadolinium',
        'atm_no'=>'64',
        'symbol'=> 'Gd',
        'mass'=>'157.25',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Terbium',
        'atm_no'=>'65',
        'symbol'=> 'Tb',
        'mass'=>'158.9253',
        'type'=>'' ,  
    ),
       array(
     'name'=>'Dysprosium',
        'atm_no'=>'66',
        'symbol'=> 'Dy',
        'mass'=>'162.5',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Holmium',
        'atm_no'=>'67',
        'symbol'=> 'Ho',
        'mass'=>'164.9303',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Erbium',
        'atm_no'=>'68',
        'symbol'=> 'Er',
        'mass'=>'167.259',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Thulium',
        'atm_no'=>'69',
        'symbol'=> 'Tm',
        'mass'=>'168.9342',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Ytterbium',
        'atm_no'=>'70',
        'symbol'=> 'Yb',
        'mass'=>'173.04',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Lutetium',
        'atm_no'=>'71',
        'symbol'=> 'Lu',
        'mass'=>'174.967',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Hafnium',
        'atm_no'=>'72',
        'symbol'=> 'Hf',
        'mass'=>'178.49',
        'type'=>'metal' ,  
    ),
       array(
     'name'=>'Tantalum',
        'atm_no'=>'73',
        'symbol'=> 'Ta',
        'mass'=>'180.9479',
        'type'=>'metal' ,  
    ),
       array(
     'name'=>'Rhenium',
        'atm_no'=>'75',
        'symbol'=> 'Re',
        'mass'=>'186.207',
        'type'=>'metal' ,  
    ),
       array(
     'name'=>'Osmium',
        'atm_no'=>'76',
        'symbol'=> 'Os',
        'mass'=>'190.23',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Iridium',
        'atm_no'=>'77',
        'symbol'=> 'Ir',
        'mass'=>'192.217',
        'type'=>'metal' ,  
    ),
       array(
     'name'=>'Thallium',
        'atm_no'=>'81',
        'symbol'=> 'Tl',
        'mass'=>'204.3833',
        'type'=>'metal' ,  
    ),
      array(
     'name'=>'Bismuth',
        'atm_no'=>'83',
        'symbol'=> 'Bi',
        'mass'=>'208.9804',
        'type'=>'metal' ,  
    ),
       array(
     'name'=>'Polonium',
        'atm_no'=>'84',
        'symbol'=> 'Po',
        'mass'=>'209',
        'type'=>'metalloid' ,  
    ),
        array(
     'name'=>'Astatine',
        'atm_no'=>'85',
        'symbol'=> 'At',
        'mass'=>'210',
        'type'=>'metalloid' ,  
    ),
       array(
     'name'=>'Radon',
        'atm_no'=>'86',
        'symbol'=> 'Rn',
        'mass'=>'222',
        'type'=>'nobelgas' ,  
    ),
      array(
     'name'=>'Francium',
        'atm_no'=>'87',
        'symbol'=> 'Fr',
        'mass'=>'223',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Radium',
        'atm_no'=>'88',
        'symbol'=> 'Ra',
        'mass'=>'226',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Actinium',
        'atm_no'=>'89',
        'symbol'=> 'Ac',
        'mass'=>'227',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Thorium',
        'atm_no'=>'90',
        'symbol'=> 'Th',
        'mass'=>'232.0381',
        'type'=>'' ,  
    ),
      array(
     'name'=>'Protactinium',
        'atm_no'=>'91',
        'symbol'=> 'Pa',
        'mass'=>'231.0359',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Uranium',
        'atm_no'=>'92',
        'symbol'=> 'U',
        'mass'=>'238.6289',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Neptunium',
        'atm_no'=>'93',
        'symbol'=> 'Np',
        'mass'=>'237',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Plutonium',
        'atm_no'=>'94',
        'symbol'=> 'Pu',
        'mass'=>'244',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Americium',
        'atm_no'=>'95',
        'symbol'=> 'Am',
        'mass'=>'243',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Curium',
        'atm_no'=>'96',
        'symbol'=> 'Cm',
        'mass'=>'247',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Californium',
        'atm_no'=>'98',
        'symbol'=> 'Cf',
        'mass'=>'251',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Einsteinium',
        'atm_no'=>'99',
        'symbol'=> 'Es',
        'mass'=>'252',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Fernium',
        'atm_no'=>'100',
        'symbol'=> 'Fm',
        'mass'=>'257',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Mendelevium',
        'atm_no'=>'101',
        'symbol'=> 'Md',
        'mass'=>'258',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Nobelium',
        'atm_no'=>'102',
        'symbol'=> 'No',
        'mass'=>'259',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Lawrencium',
        'atm_no'=>'103',
        'symbol'=> 'Lr',
        'mass'=>'262',
        'type'=>'' ,  
    ),
     array(
     'name'=>'Rutherfordium',
        'atm_no'=>'104',
        'symbol'=> 'Rf',
        'mass'=>'261',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Dubnium',
        'atm_no'=>'105',
        'symbol'=> 'Db',
        'mass'=>'262',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Seaborgium',
        'atm_no'=>'106',
        'symbol'=> 'Sg',
        'mass'=>'266',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Bohrium',
        'atm_no'=>'107',
        'symbol'=> 'Bh',
        'mass'=>'264',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Hassium',
        'atm_no'=>'108',
        'symbol'=> 'Hs',
        'mass'=>'277',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Meitnreium',
        'atm_no'=>'109',
        'symbol'=> 'Mt',
        'mass'=>'268',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Darmstadtium',
        'atm_no'=>'110',
        'symbol'=> 'Ds',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Roentgenium',
        'atm_no'=>'111',
        'symbol'=> 'Rg',
        'mass'=>'272',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Copernicium',
        'atm_no'=>'112',
        'symbol'=> 'Cn',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Nihonium',
        'atm_no'=>'113',
        'symbol'=> 'Nh',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Flerovium',
        'atm_no'=>'114',
        'symbol'=> 'Fl',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Moscovium',
        'atm_no'=>'115',
        'symbol'=> 'Mc',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Livermorium',
        'atm_no'=>'116',
        'symbol'=> 'Lv',
        'mass'=>'',
        'type'=>'metal' ,  
    ),
     array(
     'name'=>'Tennessine',
        'atm_no'=>'117',
        'symbol'=> 'Ts',
        'mass'=>'',
        'type'=>'metalloid' ,  
    ),
     array(
     'name'=>'Oganesson',
        'atm_no'=>'118',
        'symbol'=> 'Og',
        'mass'=>'',
        'type'=>'nobelgas' ,  
    ),
    );
    foreach ($elements as $ele) {
   
    $query="INSERT INTO elements(name,atomic_number,symbol,atomic_weight,element_type)VALUES('$ele[name]','$ele[atm_no]','$ele[symbol]','$ele[mass]','$ele[type]')";
    queryMysql($query);
echo 'iserted into datadase';       
}